version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:12345@db/crud_copilot
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/__pycache__/  # Prevent caching issues during hot reloading
    command: flask run --host=0.0.0.0 --port=5000 --reload  # Enable hot reloading

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: crud_copilot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
