version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
    command: >
      sh -c "flask db upgrade &&
             flask run --host=0.0.0.0 --port=5000"

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: crud_copilot
    ports:
      - "5432:5432"

volumes:
  postgres_data:
